# Generated by Django 5.0.1 on 2024-01-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='OTT',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='SMS',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='total_data',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='voice',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='data',
            field=models.CharField(choices=[('1GB/Day', '1GB'), ('1.5GB/Day', '1.5GB'), ('2GB/Day', '2GB'), ('2.5GB/Day', '2.5GB'), ('3GB/Day', '3GB')], max_length=50),
        ),
    ]
