# Generated by Django 5.0.1 on 2024-01-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0003_plan_ott_plan_sms_plan_total_data_plan_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='data',
            field=models.CharField(choices=[('1GB', '1GB/Day'), ('1.5GB', '1.5GB/Day'), ('2GB', '2GB/Day'), ('2.5GB', '2.5GB/Day'), ('3GB', '3GB/Day')], max_length=50),
        ),
    ]
