# Generated by Django 5.0.1 on 2024-01-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0004_alter_plan_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pdetails',
        ),
    ]
