# Generated by Django 5.0.1 on 2024-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0005_remove_plan_pdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
