# Generated by Django 5.0.1 on 2024-01-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0007_customer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
