# Generated by Django 5.0.1 on 2024-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0008_remove_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmobile', models.BigIntegerField()),
            ],
        ),
    ]
