# Generated by Django 5.0.1 on 2024-01-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0009_recharge_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='add_on',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='family',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
